package test;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class RegisterPage {

private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
 driver = new ChromeDriver();
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
 driver.quit();
}
@Test
public void registeration() {
 // Test name: registeration
 // Step # | name | target | value
 // 1 | open | https://demo.nopcommerce.com/ | 
 driver.get("https://demo.nopcommerce.com/");
 // 2 | setWindowSize | 1920x1040 | 
 driver.manage().window().setSize(new Dimension(1920, 1040));
 // 3 | click | linkText=Register | 
 driver.findElement(By.linkText("Register")).click();
 // 4 | click | id=gender-male | 
 driver.findElement(By.id("gender-male")).click();
 // 5 | click | id=FirstName | 
 driver.findElement(By.id("FirstName")).click();
 // 6 | type | id=FirstName | Yousef
 driver.findElement(By.id("FirstName")).sendKeys("Yousef");
 // 7 | click | id=LastName | 
 driver.findElement(By.id("LastName")).click();
 // 8 | type | id=LastName | Ali
 driver.findElement(By.id("LastName")).sendKeys("Ali");
 // 9 | click | name=DateOfBirthDay | 
 driver.findElement(By.name("DateOfBirthDay")).click();
 // 10 | select | name=DateOfBirthDay | label=20
 {
   WebElement dropdown = driver.findElement(By.name("DateOfBirthDay"));
   dropdown.findElement(By.xpath("//option[. = '20']")).click();
 }
 // 11 | click | name=DateOfBirthDay | 
 driver.findElement(By.name("DateOfBirthDay")).click();
 // 12 | click | name=DateOfBirthMonth | 
 driver.findElement(By.name("DateOfBirthMonth")).click();
 // 13 | select | name=DateOfBirthMonth | label=January
 {
   WebElement dropdown = driver.findElement(By.name("DateOfBirthMonth"));
   dropdown.findElement(By.xpath("//option[. = 'January']")).click();
 }
 // 14 | click | name=DateOfBirthMonth | 
 driver.findElement(By.name("DateOfBirthMonth")).click();
 // 15 | click | name=DateOfBirthYear | 
 driver.findElement(By.name("DateOfBirthYear")).click();
 // 16 | select | name=DateOfBirthYear | label=1993
 {
   WebElement dropdown = driver.findElement(By.name("DateOfBirthYear"));
   dropdown.findElement(By.xpath("//option[. = '1993']")).click();
 }
 // 17 | click | name=DateOfBirthYear | 
 driver.findElement(By.name("DateOfBirthYear")).click();
 // 18 | click | id=Email | 
 driver.findElement(By.id("Email")).click();
 // 19 | type | id=Email | yusuf.alquran8@gmail.com
 driver.findElement(By.id("Email")).sendKeys("yusuf9889779@gmail.com");
 // 20 | click | id=Company | 
 driver.findElement(By.id("Company")).click();
 // 21 | type | id=Company | MIU
 driver.findElement(By.id("Company")).sendKeys("MIU");
 // 22 | click | id=Newsletter | 
 driver.findElement(By.id("Newsletter")).click();
 // 23 | click | id=Password | 
 driver.findElement(By.id("Password")).click();
 // 24 | type | id=Password | 6t@4tV96nPVZE5W
 driver.findElement(By.id("Password")).sendKeys("6t@4tV96nPVZE5W");
 // 25 | type | id=ConfirmPassword | 6t@4tV96nPVZE5W
 driver.findElement(By.id("ConfirmPassword")).sendKeys("6t@4tV96nPVZE5W");
 // 26 | click | id=register-button | 
 driver.findElement(By.id("register-button")).click();
}
}

